TRUNCATE TABLE voto RESTART IDENTITY CASCADE;
TRUNCATE TABLE sessao_votacao RESTART IDENTITY CASCADE;
TRUNCATE TABLE associado RESTART IDENTITY CASCADE;
TRUNCATE TABLE pauta RESTART IDENTITY CASCADE;
